package scenario

import (
	"time"

	"openshock/backend/internal/core"
	"openshock/backend/internal/storestate"
)

func Snapshot() storestate.MemoryStoreSnapshot {
	now := time.Now().UTC().Format(time.RFC3339)

	agents := []core.Agent{
		{
			WorkspaceID: "ws_01",
			ID:          "agent_lead",
			Name:        "Lead_Architect",
			Prompt:      "全局规划者，负责先厘清目标、约束、依赖和阶段性里程碑，再把工作切给合适的 agent，偏好先建模再行动。",
		},
		{
			WorkspaceID: "ws_01",
			ID:          "agent_systems",
			Name:        "Systems_Agent_01",
			Prompt:      "系统侦探，优先做证据驱动的排查，喜欢收集上下文、复现路径和指标信号，再给出系统层面的定位和修复建议。",
		},
		{
			WorkspaceID: "ws_01",
			ID:          "agent_guardian",
			Name:        "Guardian_Bot",
			Prompt:      "风险守门人，在涉及高风险改动、审批边界或跨模块影响时会更谨慎，偏好从失败场景和回滚成本来审视方案。",
		},
		{
			WorkspaceID: "ws_01",
			ID:          "agent_shell",
			Name:        "Shell_Runner",
			Prompt:      "执行型工程师，适合承担具体实现和命令执行工作，习惯边做边验证，重视把抽象计划转换成可交付的代码和产物。",
		},
	}

	rooms := []core.RoomSummary{
		{WorkspaceID: "ws_01", ID: "room_001", Kind: "discussion", Title: "Announcements", UnreadCount: 1},
		{WorkspaceID: "ws_01", ID: "room_002", Kind: "discussion", Title: "Roadmap", UnreadCount: 1},
		{WorkspaceID: "ws_01", ID: "room_101", IssueID: "issue_101", Kind: "issue", Title: "Fix Memory Leak", UnreadCount: 3},
		{WorkspaceID: "ws_01", ID: "room_102", IssueID: "issue_102", Kind: "issue", Title: "Task Board Refresh", UnreadCount: 1},
		{WorkspaceID: "ws_01", ID: "room_103", IssueID: "issue_103", Kind: "issue", Title: "Latency Audit", UnreadCount: 0},
		{WorkspaceID: "ws_01", ID: "room_104", DirectAgentID: "agent_lead", Kind: "direct_message", Title: "Lead_Architect", UnreadCount: 0},
		{WorkspaceID: "ws_01", ID: "room_105", DirectAgentID: "agent_systems", Kind: "direct_message", Title: "Systems_Agent_01", UnreadCount: 0},
		{WorkspaceID: "ws_01", ID: "room_106", DirectAgentID: "agent_guardian", Kind: "direct_message", Title: "Guardian_Bot", UnreadCount: 0},
		{WorkspaceID: "ws_01", ID: "room_107", DirectAgentID: "agent_shell", Kind: "direct_message", Title: "Shell_Runner", UnreadCount: 0},
	}

	return storestate.MemoryStoreSnapshot{
		Workspaces: []core.Workspace{
			{
				ID:           "ws_01",
				Name:         "OpenShock.ai",
				RepoBindings: []core.WorkspaceRepoBinding{},
			},
		},
		DefaultWorkspaceID: "ws_01",
		DefaultRoomIDs: map[string]string{
			"ws_01": "room_001",
		},
		DefaultIssueIDs: map[string]string{
			"ws_01": "issue_101",
		},
		Rooms:  rooms,
		Agents: agents,
		Runtimes: []core.Runtime{
			{ID: "rt_local", Name: "Local MBP", Status: "online", Provider: "codex", SlotCount: 2, ActiveSlots: 0, LastHeartbeatAt: now},
			{ID: "rt_ci", Name: "CI Lane", Status: "busy", Provider: "codex", SlotCount: 1, ActiveSlots: 1, LastHeartbeatAt: now},
		},
		Issues: []core.Issue{
			{
				WorkspaceID: "ws_01",
				ID:          "issue_101",
				Title:       "Fix memory leak in observer pipeline",
				Status:      "in_progress",
				Priority:    "urgent",
				Summary:     "The production observer handler keeps retaining stale buffers under burst load.",
			},
			{
				WorkspaceID: "ws_01",
				ID:          "issue_102",
				Title:       "Refresh task board layout and counters",
				Status:      "todo",
				Priority:    "high",
				Summary:     "Align board density and state grouping with the new collaboration shell.",
			},
			{
				WorkspaceID: "ws_01",
				ID:          "issue_103",
				Title:       "Audit runtime latency spikes",
				Status:      "in_review",
				Priority:    "medium",
				Summary:     "Trace intermittent latency on background sync runners and reduce false alerts.",
			},
		},
		MessagesByRoom: map[string][]core.Message{
			"room_001": {
				{
					ID:        "msg_announcement_001",
					ActorType: "system",
					ActorName: "OpenShock",
					Kind:      "summary",
					Body:      "Workspace initialized. Use this room for cross-team announcements and decisions that everyone should see.",
					CreatedAt: "2026-04-05T07:40:00Z",
				},
			},
			"room_002": {
				{
					ID:        "msg_roadmap_001",
					ActorType: "system",
					ActorName: "OpenShock",
					Kind:      "summary",
					Body:      "Track roadmap direction here: milestones, sequencing, and scope changes across issues.",
					CreatedAt: "2026-04-05T07:45:00Z",
				},
			},
			"room_101": {
				{
					ID:        "msg_001",
					ActorType: "agent",
					ActorName: "Lead_Architect",
					Kind:      "summary",
					Body:      "I isolated the heap growth to the observer handoff path. We need one branch for diagnosis and one for a retention guard fix.",
					CreatedAt: "2026-04-05T08:00:00Z",
				},
				{
					ID:        "msg_002",
					ActorType: "agent",
					ActorName: "Systems_Agent_01",
					Kind:      "log",
					Body:      "Diagnostic initiated. Captured a strong reference chain from observer cache to retired event frames.",
					CreatedAt: "2026-04-05T08:03:00Z",
				},
				{
					ID:        "msg_003",
					ActorType: "agent",
					ActorName: "Guardian_Bot",
					Kind:      "blocked",
					Body:      "Quick action required: branch hotfix touches guarded billing code and needs approval before integration.",
					CreatedAt: "2026-04-05T08:06:00Z",
				},
			},
			"room_102": {},
			"room_103": {},
			"room_104": {},
			"room_105": {},
			"room_106": {},
			"room_107": {},
		},
		AgentSessions:         []core.AgentSession{},
		AgentTurns:            []core.AgentTurn{},
		AgentTurnOutputChunks: []core.AgentTurnOutputChunk{},
		AgentTurnToolCalls:    []core.AgentTurnToolCall{},
		HandoffRecords:        []core.HandoffRecord{},
		Tasks: []core.Task{
			{
				WorkspaceID:     "ws_01",
				ID:              "task_diag",
				IssueID:         "issue_101",
				Title:           "Trace retained observer frames",
				Description:     "Confirm the retention path and produce a targeted fix note.",
				Status:          "integrated",
				AssigneeAgentID: "agent_systems",
				BranchName:      "issue-101/task-diag",
				RunCount:        2,
			},
			{
				WorkspaceID:     "ws_01",
				ID:              "task_guard",
				IssueID:         "issue_101",
				Title:           "Add retention guard around handoff queue",
				Description:     "Patch the observer queue to drop stale references on handoff.",
				Status:          "in_progress",
				AssigneeAgentID: "agent_shell",
				BranchName:      "issue-101/task-guard",
				RunCount:        1,
			},
			{
				WorkspaceID:     "ws_01",
				ID:              "task_review",
				IssueID:         "issue_101",
				Title:           "Review billing touchpoints before merge",
				Description:     "Validate branch changes near approval-sensitive billing logic.",
				Status:          "todo",
				AssigneeAgentID: "agent_guardian",
				BranchName:      "issue-101/task-review",
				RunCount:        0,
			},
			{
				WorkspaceID:     "ws_01",
				ID:              "task_board_ui",
				IssueID:         "issue_102",
				Title:           "Compress board columns and badge layout",
				Description:     "Bring the task board in line with the latest shell design.",
				Status:          "todo",
				AssigneeAgentID: "agent_lead",
				BranchName:      "issue-102/task-board-ui",
				RunCount:        0,
			},
		},
		Runs: []core.Run{
			{
				WorkspaceID:   "ws_01",
				ID:            "run_diag_01",
				TaskID:        "task_diag",
				AgentID:       "agent_systems",
				RuntimeID:     "rt_local",
				Status:        "completed",
				Title:         "Diagnostic trace on observer cache",
				OutputPreview: "Captured heap path from observer cache to retired event frames.",
			},
			{
				WorkspaceID:   "ws_01",
				ID:            "run_guard_01",
				TaskID:        "task_guard",
				AgentID:       "agent_shell",
				RuntimeID:     "rt_ci",
				Status:        "approval_required",
				Title:         "Patch retention guard in handoff queue",
				OutputPreview: "Proposed patch touches guarded billing code. Awaiting approval.",
			},
			{
				WorkspaceID:   "ws_01",
				ID:            "run_review_01",
				TaskID:        "task_review",
				AgentID:       "agent_guardian",
				RuntimeID:     "",
				Status:        "queued",
				Title:         "Review billing touchpoints before merge",
				OutputPreview: "Queued and waiting for runtime claim.",
			},
		},
		RunOutputChunks: []core.RunOutputChunk{},
		ToolCalls:       []core.ToolCall{},
		MergeAttempts:   []core.MergeAttempt{},
		IntegrationBranches: []core.IntegrationBranch{
			{
				WorkspaceID:   "ws_01",
				ID:            "ib_issue_101",
				IssueID:       "issue_101",
				Name:          "issue-101/integration",
				Status:        "integrating",
				MergedTaskIDs: []string{"task_diag"},
			},
			{
				WorkspaceID:   "ws_01",
				ID:            "ib_issue_102",
				IssueID:       "issue_102",
				Name:          "issue-102/integration",
				Status:        "collecting",
				MergedTaskIDs: []string{},
			},
			{
				WorkspaceID:   "ws_01",
				ID:            "ib_issue_103",
				IssueID:       "issue_103",
				Name:          "issue-103/integration",
				Status:        "ready_for_delivery",
				MergedTaskIDs: []string{},
			},
		},
		DeliveryPRs: []core.DeliveryPR{
			{
				WorkspaceID: "ws_01",
				ID:          "pr_103",
				IssueID:     "issue_103",
				Title:       "Merge runtime latency audit into main",
				Status:      "open",
			},
		},
		InboxItems: []core.InboxItem{
			{
				WorkspaceID:       "ws_01",
				ID:                "inbox_001",
				Title:             "Approval Required for Branch #102",
				Kind:              "approval_required",
				Severity:          "high",
				Summary:           "The retention guard patch changes billing-adjacent logic and needs human authorization.",
				RelatedEntityType: "run",
				RelatedEntityID:   "run_guard_01",
				PrimaryActionType: "Run.approve",
			},
			{
				WorkspaceID:       "ws_01",
				ID:                "inbox_002",
				Title:             "Merge Conflict on Issue #101",
				Kind:              "merge_conflict",
				Severity:          "medium",
				Summary:           "The integration branch needs a follow-up fix before the guard task can merge cleanly.",
				RelatedEntityType: "task",
				RelatedEntityID:   "task_guard",
				PrimaryActionType: "GitIntegration.merge.approve",
			},
			{
				WorkspaceID: "ws_01",
				ID:          "inbox_003",
				Title:       "Sarah asked for help in #general",
				Kind:        "human_help",
				Severity:    "low",
				Summary:     "Review the architecture sketch before the next issue decomposition pass.",
			},
		},
		RepoWebhookEvents:       map[string]core.RepoWebhookResponse{},
		Members:                 map[string]core.Member{},
		MemberIDsByUsername:     map[string]string{},
		PasswordHashes:          map[string]string{},
		AuthSessions:            map[string]core.AuthSession{},
		RoomReadBySession:       map[string]map[string]string{},
		NextMessageID:           100,
		NextTaskID:              100,
		NextRunID:               100,
		NextRunOutputID:         100,
		NextToolCallID:          100,
		NextMergeAttemptID:      100,
		NextRuntimeID:           100,
		NextIssueID:             103,
		NextRoomID:              107,
		NextInboxID:             100,
		NextActionID:            100,
		NextAgentSessionID:      100,
		NextAgentTurnID:         100,
		NextAgentTurnOutputID:   100,
		NextAgentTurnToolCallID: 100,
		NextHandoffID:           100,
		NextAgentID:             len(agents),
		NextWorkspaceRepoID:     100,
		NextMemberID:            0,
		NextAuthSessionID:       0,
		ActionResults:           map[string]core.ActionResponse{},
	}
}
